Winter is Coming
Changes all around. Full Automation for EVERYONE. Thanks to my supports,
bug submitters and feature requesters! Enjoy.

diff --git a/Autosnort - Ubuntu/snortbarn b/Autosnort - Ubuntu/snortbarn
--- a/Autosnort - Ubuntu/snortbarn
+++ b/Autosnort - Ubuntu/snortbarn
@@ -1,62 +1,79 @@
-#! /bin/sh
-#
+#!/bin/bash
 ### BEGIN INIT INFO
-#Provides: snortbarn
-#Required-Start: $remote_fs $syslog mysql
-#Required-Stop: $remote_fs $syslog
-#Default-Start: 2 3 4 5
-#Default-Stop: 0 1 6
-#X-Interactive: true
-#Short-Description: Start Snort and Barnyard
+# Provides: snort, barnyard2
+# Required-Start: $local_fs $remote_fs $network $named $syslog $time
+# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: start and stop snort and barnyard2
+# Description: Snort is a powerful open-source Intrusion Detection System.
+# Barnyard2 is a tool for processing snort unified2 log files.
 ### END INIT INFO
 
-prog="snort"
-prog2="barnyard2"
-
-# Change these variables to suit your snort installation
 #The location of the snort binary
-SNORTD=/usr/local/snort/bin/snort
+SNORTD=snort_basedir/bin/snort
 #The location of the barnyard2 binary
 BY2D=/usr/local/bin/barnyard2
-#The sniffing interface for snort
-snort_iface=eth1
 #Command line execution options for snort
-OPTIONS="-D -u snort -g snort -c /usr/local/snort/etc/snort.conf -i $snort_iface"
+OPTIONS="-D -u snort -g snort -c snort_basedir/etc/snort.conf -i snort_iface"
 #Command line execution options for barnyard 2
-OPTIONS2="-c /usr/local/snort/etc/barnyard2.conf -d /var/log/snort -f snort.u2 -w /var/log/snort/barnyard2.waldo -D"
-
-. /lib/init/vars.sh
-. /lib/lsb/init-functions
-
-mysqld_get_param() {
-/usr/sbin/mysqld --print-defaults | tr " " "\n" | grep -- "--pid-file=" | cut -d"=" -f2
-}
+OPTIONS2="-c snort_basedir/etc/barnyard2.conf -d /var/log/snort -f snort.u2 -w /var/log/snort/barnyard2.waldo -D"
 
 do_start()
 {
-    log_daemon_msg "Starting Snort and Barnyard" ""
-    # Make sure mysql has finished starting
-    ps_alive=0
-    while [ $ps_alive -lt 1 ];
-    do
-    pidfile=`mysqld_get_param pid-file`
-    if [ -f "$pidfile" ] && ps `cat $pidfile` >/dev/null 2>&1; then ps_alive=1; fi
-    sleep 1
-    done
-
-    /sbin/ifconfig $snort_iface up -arp -multicast promisc
+    echo "Starting Snort and Barnyard" 
+    /sbin/ifconfig snort_iface up -arp -multicast promisc
     $SNORTD $OPTIONS
+	if [ $? -eq 0 ]; then
+		echo "Snort successfully started."
+		logger "Snort Started!"
+	else
+		echo "Snort failed to start!"
+	fi
     $BY2D $OPTIONS2
-    log_end_msg 0
+	if [ $? -eq 0 ]; then
+		echo "Barnyard2 successfully started."
+		logger "Barnyard2 Started!"
+	else
+		echo "Barnyard2 failed to start!"
+	fi
     return 0
+}
+
+do_status()
+{
+	pidof snort
+	if [ $? -eq 0 ]; then		
+		echo "Snort is running with a pid of `pidof snort`"
+	else
+		echo "Snort is not running."
+	fi
+	pidof barnyard2
+	if [ $? -eq 0 ]; then
+		
+		echo "Barnyard2 is running with a pid of `pidof barnyard2`"
+	else
+		echo "Barnyard2 is not running."
+	fi
 }
 
 do_stop()
 {
-    log_daemon_msg "Stopping Snort and Barnyard" ""
+    echo "Stopping Snort and Barnyard" ""
     kill $(pidof snort) 2> /dev/null
+	if [ $? -eq 0 ]; then
+		echo "Snort successfully killed."
+		logger "Killed Snort."
+	else
+		echo "Snort could not be killed! (Permissions? Already dead?)"
+	fi
     kill $(pidof barnyard2) 2> /dev/null
-    log_end_msg 0
+	if [ $? -eq 0 ]; then
+		echo "Barnyard2 successfully killed."
+		logger "Killed Barnyard2."
+	else
+		echo "Barnyard2 could not be killed! (Permissions? Already dead?)"
+	fi
     return 0
 }
 
@@ -71,8 +88,11 @@ case "$1" in
     do_stop
     do_start
     ;;
+ status)
+	do_status
+	;;
  *)
-    echo "Usage: snortbarn {start|stop|restart}" >&2
+    echo "Usage: snortbarn {start|stop|restart|status}" >&2
     exit 3
     ;;
 esac
